# Configures sensor logging
columns:    # Must align with schema.sql on columns
  - datetime
  - location
  - sensor_id
  - pm_2_5
  - pm_10
measurements:    # Syntax: start byte, num bytes, scale factor 
  pm_2_5:
    - 2
    - 2
    - 0.1
  pm_10: 
    - 4
    - 2
    - 0.1
sensor_id:    # Syntax: start byte, num_bytes 
  - 6
  - 2
port_device: /dev/ttyUSB0    # Linux USB serial port, change for Windows
message_length: 10    # Number of bytes per sensor transmission
period: 300    # Number of messages to aggregate per upload
byte_order: little # Endianness of bytes for values in the message
max_retries: 5 # How many failed uploads are permitted before process terminates
location: outside
repo_owner: air_quality_log_test    # bit.io username
repo_name: air_quality    # bit.io repo name
table_name: pm_measurements    # bit.io table name